### PR TITLE
Move C#8 and .NET Core 3 into adopt.

### PR DESCRIPTION
**Pull request by fffej**
- [x] Are you happy for the content of this change to be publicly visible?
- [x] Are all new or updated entries marked as `isNew` = `true`?
- [x] Do `radar.csv` and `radar_libraries` render correctly when viewed on Github?
- [x] Does the updated [tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Flatest-csharp%2Fradar.csv) display as you expect?
- [x] Does the updated [libraries tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%latest-csharp%2Fradar_libraries.csv) display as you expect?

### CODE REVIEW

**Comment by Greg-Smulko** [comment]
C#8 doesn't work with .NET Framework 4.7.2 (nor 4.8) in general.
Are we fine with it?

**Comment by nyctef** [comment]
> C#8 doesn't work with .NET Framework 4.7.2 (nor 4.8) in general.
> Are we fine with it?

I don't believe this is true in general - I've just created a quick console app targeting net472, using C# 8.0 and nullable reference types and it built just fine.

There are some specific C#8 features that won't be supported in net472+ (eg async streams) since they rely on code that won't be shipped with the framework, but I suspect there will be backport nuget packages which provide the code if we really need it (similar to LinqBridge / Microsoft.Bcl.Async back in the day)

Overall I'm happy with moving C#8 into adopt - I wonder if we additionally want to move nullable reference types + other features into explore/adopt as well, since they'll need quite a bit of work to be useful?

**Comment by angellaa** [comment]
Syntactic sugar features like switch expressions, new patterns, null coalescing assignment, using declarations should all work on .NET. Nullable reference types also works but you don’t get the main benefits as Microsoft do not intend to make any effort to annotate .NET. However, I read their main testing efforts is on .NET Core 3 so they do not officially support C# 8 on .NET framework.

**Comment by fffej** [comment]
Thanks for correcting me! If C#8 isn't officially supported on .NET Framework then I guess that raises some concerns.

**Comment by samblackburn** [comment]
We've already switched to C# 8 for Compare and Data Compare, most of which dual-targets netframework461 and netstandard2.0.  No problems yet, but it's useful to know that this isn't officially supported!

**Comment by angellaa** [comment]
For reference, this is the comment where I read C# 8 is not officially supported on .NET from https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8

image

**Comment by Greg-Smulko** [comment]
A good write-up of what parts from c# 8 should work on .Net Framework 4.x:
https://stu.dev/csharp8-doing-unsupported-things/

**Pull request merged**
