### PR TITLE
Move over Libraries

### PR DESCRIPTION
**Pull request by fffej**
- [x] Are you happy for the content of this change to be publicly visible?
- [x] Are all new or updated entries marked as `isNew` = `true`?
- [x] Do `radar.csv` and `radar_libraries` render correctly when viewed on Github?
- [x] Does the updated [tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Fmove-to-libraries%2Fradar.csv) display as you expect?
- [x] Does the updated [libraries tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Fmove-to-libraries%2Fradar_libraries.csv) display as you expect?

Move more blips over to the libraries tech radar.

### CODE REVIEW

**Comment by allymparker** [comment]
Looks good - I'm wondering if we could use that last quadrant for "Test frameworks"?

**Comment by adrianbanks** [comment]
:thumbsup: from me.

**Comment by TheEadie** [comment]
:+1: Looks good to me

**Comment by idursun** [comment]
Looks great! 🚀

**Pull request merged**
