### PR TITLE
Add common code style with nightly reformatting

### PR DESCRIPTION
**Pull request by Greg-Smulko**
We're going to agree on the common code style and adopt it for all active products. It includes one big reformatting upfront and configuring a TeamCity project to run code reformatting for every product every night.

## Benefits 

Consistent code style has multiple benefits, including:
- reduced cognitive load,
- obvious bugs easier to spot,
- code looks neat, so it's nicer to work with.

As Jeff put it:
> The case to auto-format code is very strong – we’ll never need to argue about tabs/spaces/formatting and can instead focus on discussions about the code itself. 

Also, having a consistent code style config across teams allows us to go faster as a division:
- no need to spend time on agreeing on the code style - as it's already agreed and accepted cross-division,
- no need to reinvent the wheel when somebody wants to introduce it in another project,
- with more and more people moving between teams it makes even more sense now than before.

Reformatting the code nightly ensures that the formatting is applied without the need for any manual actions. It means that during PR review there is no need to haggle about the code style, as it's going to be in the agreed state next morning anyway.

## Disadvantages
- Initial reformatting of code will make `git blame` more difficult.

## Tech

We're using JetBrains CleanupCode for C# and Prettier for JS/TS. 
The formatting rules are stored in `editor.config` file."

See SQL Data Catalog for reference:
- [`.editorconfig`](https://github.com/red-gate/SqlDataCatalog/blob/master/src/.editorconfig)
- [PS task](https://github.com/red-gate/SqlDataCatalog/blob/master/.build/tasks/resharper.tasks.ps1#L16) - to be moved to `Redgate.Build`
- [nightly TeamCity build](https://buildserver.red-gate.com/viewType.html?buildTypeId=CustomerDelight_SqlEstateManager_Web_ReformatCode)

## Next steps

For now, we're going to focus on C# code only.

Next step can include:
- automatic Prettier reformatting for TypeScript / JavaScript,
- formatting of JSON, Markdown, HTML and CSS/LESS/SASS, ...
- formatting of Java code bases,
- formatting of PowerShell,
- SQL formatting

## Checks

- [x] Are you happy for the content of this change to be publicly visible?
- [x] Are all new or updated entries marked as `isNew` = `true`?
- [x] Do `radar.csv` and `radar_libraries` render correctly when viewed on Github?
- [x] Does the updated [tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Fcode-reformatting-nightly%2Fradar.csv) display as you expect?
- [x] Does the updated [libraries tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Fcode-reformatting-nightly%2Fradar_libraries.csv) display as you expect?

### CODE REVIEW

**Comment by allymparker** [comment]
Wot, no SQL Formatting? :trollface: 

Love it.  Make it so.  

Would be nice to extend Prettier to JSON, Markdown, HTML and CSS/LESS/SASS too?

How about our Java code bases?

**Comment by Greg-Smulko** [comment]
I created a slack channel [#eng-code-reformatting-initiative](https://redgate.slack.com/archives/CTHNT1D8W) if we want to discuss it more there.

@allymparker , I just added the "Next steps" section to the PR description.

**Comment by nyctef** [comment]
👍 Prettier is awesome and we should use it everywhere we can.

My (probably outdated) experience with R# formatting hasn't been so great, though - the main reason being that R# preserves too much of the original code's formatting, so you still end up spending time trying to create a layout that R# will then massage into something good-looking. Does anyone know if this is still true? Does `CleanupCode.exe` have the same problem?

**Comment by Greg-Smulko** [comment]
> R# preserves too much of the original code's formatting

@nyctef 
I think it depends on the config that you have - I think that by default R# isn't so greedy in applying the style changes. Take a look at the Data Catalog `.editorconfig` - there are quite many rules specified there, and my experience is that with this it generates quite a consistent code.

I assume that `CleanupCode.exe` is the tool that R# uses under the hood.

**Comment by Greg-Smulko** [comment]
Just for a reference:
- How-to guide: https://info.red-gate.com/display/PD/Code+formatting
- GitHub board: https://github.com/orgs/red-gate/projects/28?fullscreen=true

**Pull request merged**
