### PR TITLE
Dedicated tech-debt time

### LINKED ISSUE #113: [Techniques] Dedicated tech-debt time
Experiment with different techniques of paying the technical debt. 

For instance 
- the Kaizen Rota in SQL Monitor teams: "1 person per team, every week".

### PR DESCRIPTION
**Pull request by fffej**
Resolves #113

### CODE REVIEW

**Comment by fffej** [comment]
See [preview](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2F6234c95c2c8ba1452dd8f66c87fbe0da99c637a0%2Fradar.csv)

**Comment by priyasinha** [comment]
SQL Monitor teams are trying one dedicated person from each team pairing on Technical Debt items. 
Pros:
+ Team has made some significant progress on some items which was taking months to complete.
+ People are self selecting for rota depending on their interest and things they want to learn. 
+ We aim to keep any pair for no longer than a week. 
+ We are pairing cross team which helps with cross team collaboration too. 
Cons:
- We have still not worked out what happens if one pair does not properly finish the things they started or if handover is going to be costly. 
- How do we handle work which are too big to breakdown into one week chunks. 

But overall, the initial signs are very positive.

**Comment by fffej** [comment]
Updated [preview](https://radar.thoughtworks.com/?sheetId=https://raw.githubusercontent.com/red-gate/Tech-Radar/55d7800b936d2fa9df6e2e4a538a1ad7bec03049/radar.csv)

**Comment by fffej** [comment]
Closing this PR since it's been open ages, has conflicts and doesn't reflect the current status of the issue to which it's attached

**Pull request closed without merging**
