### PR TITLE
Move mobbing to adopt

### PR DESCRIPTION
**Pull request by Dave-Rook**
- [x] Are you happy for the content of this change to be publicly visible?
- [x] Are all new or updated entries marked as `isNew` = `true`?
- [x] Does `radar.csv` render correctly when viewed on Github?
- [x] Does the [updated tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2FMove-Mobbing-To-Adopt%2Fradar.csv) display as you expect?

#281 contains the conversation related to this PR

### CODE REVIEW

**Comment by Dave-Rook** [comment]
Please do NOT merge yet... questions have risen but are not public yet :)

**Comment by fffej** [comment]
It'd be great to get the dialog public so we can all understand why (or why not) we should use particularly tech/practices. Maybe use an Issue to track?

**Comment by Dave-Rook** [comment]
I had `help wanted` label which was answered by https://github.com/red-gate/Tech-Radar/issues/281

**Comment by twalsh92** [comment]
I think the discussion in #281 shows there's plenty of support for moving Mob Programming to _Adopt_.  I've updated the description to reflect its current state. @fffej shall we merge this?

**Pull request merged**
