### PR TITLE
Refresh the Tech Radar

### PR DESCRIPTION
**Pull request by fffej**
I'd like to make the Tech Radar a bit clearer, so I've started by updating `README.md`.

The Tech Radar at the moment isn't very clear - it's got a mix of technologies new and old and it doesn't provide clarity on what we should be using. For example, it clearly states that "RavenDB" is in retire, but it's not a choice that any product is facing and it doesn't give a clear alternative.

I'd like to get fewer things on the tech radar that make more difference.

Thoughts / comments appreciated.

### CODE REVIEW

**Comment by fffej** [comment]
I'd love more feedback on this.

If we do the Tech Radar right for Redgate then it should
* Support teams making better decisions for Redgate's future 
* Provide clear guidance and direction on skills to learn for the future
* Help prioritize work on retiring / renewing technology.

It isn't doing this at the moment - why? 😄

**Comment by nyctef** [comment]
I'm not sure about limiting the radar to currently-developed products only - for example, if a team were asked to pick up an older product again, then I think the tech radar should be a useful tool for that dev team to push back and say "ok, we actually need time to fix RavenDB first" or similar. It might also still be worth documenting those sorts of decisions for the future? It might be obvious now that RavenDB "wouldn't possibly be considered", but that's knowledge which gets lost over time.

For me, though, the bigger problem with the tech radar (and codingguidelines, and ArchitectureDecisions, and so on) is just a general lack of engagement. If we just had a higher proportion of people reading, using and contributing to these resources then they would become inherently much more useful. I have no idea how to improve this, though - it seems like a chicken-and-egg kind of problem :/

**Comment by fffej** [comment]
Those are fair comments @nyctef

I'm worried you can't see the wood for the trees with the Tech Radar as it stands. For example, what does the tech radar tell you about our web stack? (other than it's fragmented!). The motivation behind thinning it out would be to focus on the decisions that really matter (and there might only be a handful of those).

As another example, for the RavenDB thing I'd rather remove all the historical negatives and replace that some default positive guidance on what to choose (e.g. store all state in a RDBMS).

**Comment by allymparker** [comment]
Totally agree with the change of definition for techniques and removing the "soft"/team/project techniques from the tech radar.

I suppose my diagnosis of the "wood for the trees" is that (arguably) there's a lot in the top level radar that i'd argue could be pushed down into the the libraries radar eg Babel, testing frameworks... or simply be removed eg JSON, XML

WRT to remove things from retire, if we don't remove things from the radar it'll just grow.  

Although the Radar is source controlled and we could use `git grep` the `rev-list` to search for previous items, it's not massively intuitive.  

Perhaps taking quarterly "snap shots" could help, the same way Thoughtworks do?  Or a "Retired" folder with mini ADR like entries? At least then it would be easily searchable on github

**Comment by allymparker** [comment]
Why not drop 021070fff78c6599be2f3e36e0e21729149d6813 to get the rest of the changes in for now?

**Comment by fffej** [comment]
@allymparker I think pushing some stuff down is a really sensible next step (and it shouldn't be controversial since it's just moving, not changing anything).

I'll have a crack at that in a separate PR if people are OK with the `README.md` changes?

**Pull request merged**
