### PR TITLE
Move semantic ui to Endure

### PR DESCRIPTION
**Pull request by fffej**
- [x] Are you happy for the content of this change to be publicly visible?
- [x] Are all new or updated entries marked as `isNew` = `true`?
- [x] Do `radar.csv` and `radar_libraries` render correctly when viewed on Github?
- [x] Does the updated [tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Fmove-semantic-ui%2Fradar.csv) display as you expect?
- [x] Does the updated [libraries tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Fmove-semantic-ui%2Fradar_libraries.csv) display as you expect?

[Semantic UI for React](https://github.com/Semantic-Org/Semantic-UI-React) is no longer under active development and we don't recommend it for new development.

Since it is [widely used](https://codesearch.red-gate.com/?q=semantic-ui-react&i=nope&files=&excludeFiles=&repos=*) and has minimal coupling I propose moving it to Endure.

### CODE REVIEW

**Comment by Greg-Smulko** [comment]
FYI @andrew-farries 

@fffej , is "no longer under active development" the only reason for moving it to Endure?
What's the context of it? Consolidating Honeycomb, or... ?

**Comment by nyctef** [comment]
Do we currently have any preferred alternative?

**Comment by allymparker** [comment]
The honeycomb CoP are currently working looking into ways to help us have a more consistent UIs across our products, increase the speed at which interfaces can be created, reduce UI rework and provide an incremental migration approach.  Part of this project is looking at the state of the available UI technologies/libraries.

The HC SemanticUI library is only partially styled and is not particularly well customised (There is a lot of emphasis on hard pixel sizes the last time I looked which made scaling inconsistent/nonexistent)

We would also like to have a looser coupling between the styling and JS library to allow a migration path that doesn't necessarily require a move to React.

**Comment by fffej** [comment]
Sorry @Greg-Smulko I meant to add more context to the original PR, but I think @allymparker has answered (thank you!).

@nyctef In terms of alternatives "not yet" is the answer, but there's more information on some of the contenders in the [#honeycomb-community](https://redgate.slack.com/archives/C0121SADSK1) channel.

**Comment by nyctef** [comment]
This is probably overly nitpicky, but does that mean semantic-ui-react is still our default choice for any new stuff in the meantime? I'm totally on board with moving it into endure/retire, but it feels like ideally we should have an "adopt" entry for this problem until there's something better

**Comment by Greg-Smulko** [comment]
Bump @allymparker @fffej . Good to merge or should we answer @nyctef's question first?

**Comment by fffej** [comment]
There's a bit of work going on in the #honeycomb-community channel that I hope will lead to use making a deliberate choice about what should be adopt. I was hoping we could get that guidance before we merge.

**Comment by Greg-Smulko** [comment]
As per https://redgate.slack.com/archives/C1BJZEAV6/p1593428457242600:
> Jeff Foster confirmed that TailwindCSS will replace Semantic UI as our React library of choice.

It means that we can revisit this PR, right?

**Comment by andrew-farries** [comment]
This is an interesting topic. See [this thread](https://redgate.slack.com/archives/C0121SADSK1/p1594206753255400) on Slack yesterday:

> Hello honeycombers :honeycomb-cop: I've been following your discussions about a new basis for honeycomb app development and reading through the excellent documentation in here. On the Sharks team we are about to start building a new Estate Management prototype, which will need a web UI. The recommendation is to use Tailwind CSS for new web UIs, but this raises some issues:
> * Right now, Tailwind CSS alone would slow us down because we need a more-or-less complete component library to build with. I understand the intention is to form a team to build a react component library on top of it, but that will obviously take time.
> * Estate Management is a prototype project, so the speed with which we can build is the single most important factor.

> With the constraints listed above, it seems to me that going with Tailwind CSS and building our own components on top is not a viable solution for us at this stage. Given that, we'd probably want to go with either Semantic UI, Fomantic UI, Bootstrap React or Ant Design to build the EM prototype. We have experience on the team with Semantic UI, so we'd probably be inclined to default to that or the Fomantic community fork.

> Does this sound like a reasonable conclusion to people?

Tailwind CSS is not a drop-in replacement for Semantic UI React; it is a CSS library, not a react component library. The work to build a component library on top of Tailwind (whether in-house or externally) still needs to happen before a team intending to build a react front-end can use it without incurring the cost of developing the components themselves.

On the Sharks, we've just started building an Estate Management prototype using SemanticUI React because of the the 3 options open to us:

* Incur the cost of building our own components on top of Tailwind
* Introduce another React component library into the RG tech stack
* Continue with the unmaintained (but largely feature complete) SemanticUI React

the third option is the least bad.

Moving SemanticUI React into endure at this stage feels premature as it leaves a void for anyone wanting to put together a react front-end *right now*.

**Comment by fffej** [comment]
I agree, we're not in a position to move Semantic UI back to `Endure`, until we make it more appealing to use an alternative.

I intend to close this pull request unless anyone tells me otherwise by 10/7/2020.

**Pull request closed without merging**
