### PR TITLE
Split libraries from radar

### LINKED ISSUE #261: Rename category "Languages and frameworks"
Rename category "Languages and frameworks" to "Languages, frameworks and libraries".

In this category, there is a lot of libraries, but it's confusing whether a library should be in the category "Languages and frameworks" or "Tools". An example here: #259.

### PR DESCRIPTION
**Pull request by garethbragg**
- [x] Are you happy for the content of this change to be publicly visible?
- [x] Are all new or updated entries marked as `isNew` = `true`?
- [x] Do `radar.csv` and `radar_libraries` render correctly when viewed on Github?
- [x] Does the updated [tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Fsplit-libraries-from-radar%2Fradar.csv) display as you expect?
- [x] Does the updated [libraries tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Fsplit-libraries-from-radar%2Fradar_libraries.csv) display as you expect?

To resolve #261

I've had a stand at picking out any libraries from `radar.csv` and moving them to `libraries_radar.csv`.

_Some of these will almost certainly be wrong, so please review the diff_.

I've done each move in an atomic commit, so this will hopefully be easy to review (and not completely awful to amend when necessary).

### CODE REVIEW

**Comment by fffej** [comment]
I'm not sure on this.

Ally introdued the "libraries" radar to handle the "noise". However moving them just moves the noise!

To be honest, I'd personally go the other way and have a single radar. Perhaps some of these are so fine-grained they should be removed completely? Maybe we need a process for "fading" blips as Thoughtworks do?

**Comment by garethbragg** [comment]
I'm also not sure, but that issue has been around for a while and nobody had suggested anything better than this.

Totally happy to ditch this change if we want to go a different route.

**Comment by nyctef** [comment]
I think it's useful to have _something_ for libraries - mostly just to avoid bikeshedding around "should we pick Ninject or Autofac"-type questions. Relegating them to their own little radar (like we've done here) makes sense to me, although maybe a radar isn't the best format.

Removing stuff over time is probably sensible, but I think we'd need a way of displaying old radars like thoughtworks do, so that the information is still searchable (just in case someone decides [they want to bring back story points](https://github.com/red-gate/Tech-Radar/pull/277) or something like that). This wouldn't need to be complicated - possibly just a list of links in the readme to specific versions of the radar?

**Comment by garethbragg** [comment]
I'll try to get this into a merge-able state.

**Comment by garethbragg** [comment]
_Should now be in a merge-able state_

**Pull request merged**
