### PR TITLE
Fade the obvious

### PR DESCRIPTION
**Pull request by fffej**
- [x] Are you happy for the content of this change to be publicly visible?
- [x] Are all new or updated entries marked as `isNew` = `true`?
- [x] Do `radar.csv` and `radar_libraries` render correctly when viewed on Github?
- [x] Does the updated [tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Ffade-the-obvious%2Fradar.csv) display as you expect?
- [x] Does the updated [libraries tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Ffasde-the-obvious%2Fradar_libraries.csv) display as you expect?

### CODE REVIEW

**Comment by fffej** [comment]
@red-gate/lead-software-engineers I've tried to remove out blips that add no useful value to teams. Please feel free to push more (or disagree with the ones I've added)

**Comment by garethbragg** [comment]
My only _slight_ concern is removing the _Adopt_ items as suggested.

They are entirely obvious to us, but how much value is there in being explicit for newcomers or the outside world (perhaps engineers who are in the process of applying to join Redgate)?

**Comment by juliahayward** [comment]
True, there are two possible purposes - to guide RG teams, and to inform the rest of the world. That feels like we need two radars rather than mashing them together, for clarity's sake?

And perhaps we should leave Raven in *Retire*, in recognition of how much of a fight it's put up against being retired? :trollface:

**Comment by fffej** [comment]
I'm going to close this in favour of smaller commits that people agree on 😄

**Pull request closed without merging**
