### PR TITLE
Add a note about using React hooks

### PR DESCRIPTION
**Pull request by andrew-farries**
Add a note to the React entry to say that we prefer to write components using functions and hooks rather than classes. See the discussion [here](https://github.com/red-gate/ArchitectureDecisions/pull/8).

---
- [x] Are you happy for the content of this change to be publicly visible?
- [x] Are all new or updated entries marked as `isNew` = `true`?
- [x] Does `radar.csv` render correctly when viewed on Github?
- [x] Does the [updated tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Fuse-react-hooks%2Fradar.csv) display as you expect?

### CODE REVIEW

**Comment by santiaago** [comment]
I disagree with this, it is too granular for a tech-radar decision IMO. I think teams should be able to choose whichever style they like to write their components, without feeling compelled to follow a **stylistic** choice.

Also, I thought hooks where still in alpha but could not find any information about this in reacts website, is it now no longer alpha? can you link to that?

**Comment by Greg-Smulko** [comment]
@santiaago, 
> can you link to that?
it's in the description of the referenced PR, see: https://reactjs.org/docs/hooks-intro.html

**Comment by santiaago** [comment]
I already saw that, it does not say its no longer alpha I thought I saw a place that say it was on alpha

**Comment by nyctef** [comment]
> I disagree with this, it is too granular for a tech-radar decision IMO. I think teams should be able to choose whichever style they like to write their components, without feeling compelled to follow a **stylistic** choice.

I guess it depends what you mean by "stylistic". This isn't something trivial like variable naming or brace placement; it's a new technique for writing code that will take time and effort to learn, but we think is worthwhile to do anyway, and it's probably worth the cost of trying to be consistent between codebases for (at least for product division code?)

Obviously there's a huge gray area between "this is really important, we're going to mandate that everyone does this" and "this is really trivial, just do whatever (but be consistent within a project at least)". For me this feels equivalent to something like preferring `async` over `task.ContinueWith` which [we do have guidelines for](https://github.com/red-gate/CSharpGuidelines/blob/4c7b90a875cb4533484a12706f590f53281ddb4c/_pages/2200_FrameworkGuidelines.md#-favor-asyncawait-over-task-continuations-rg2235-).

I agree it's probably too granular for the tech-radar, though - if we had to list out every bit of react style we thought was a good idea, we'd run out of space here very quickly. It'd be nice to have a web equivalent for CSharpGuidelines, especially since we have much less experience building web apps generally and it'd be useful to write down good ideas as we go.

@fffej What do you think? :)

**Comment by fffej** [comment]
I agree that this doesn't belong in the Tech Radar (that should be about choices, not how to use them).

I think @nyctef is right, at some point we're going to need to start getting some web guidelines together.

I'm going to close this pull request without merging it and I've opened up a referenced issue about coding guidelines.

**Pull request closed without merging**
