### PR TITLE
Log4net is now both unmaintained and insecure

### PR DESCRIPTION
**Pull request by samblackburn**
- [x] Are you happy for the content of this change to be publicly visible?
- [x] Are all new or updated entries marked as `isNew` = `true`?
- [x] Do `radar.csv` and `radar_libraries` render correctly when viewed on Github?
- [x] Does the updated [tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Fretire-log4net%2Fradar.csv) display as you expect?
- [x] Does the updated [libraries tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Fretire-log4net%2Fradar_libraries.csv) display as you expect?

### CODE REVIEW

**Comment by samblackburn** [comment]
Note: Both linked pages are stuck on "building your radar" for me.  Did I get the links wrong?

**Comment by Greg-Smulko** [comment]
> Note: Both linked pages are stuck on "building your radar" for me. Did I get the links wrong?

Should be fine now (copied from another PR and updated the links manually).

**Comment by TheEadie** [comment]
This looks like a fun one: https://codesearch.red-gate.com/?q=log4net.dll&i=nope&files=&excludeFiles=&repos=.*

A search for just `log4net` returns too many results for code-search to display them.

We also seem to have a wrapper around it in https://github.com/red-gate/RedGate.Logging which is widely used by both product and core. It feels like we should be killing that too.

**Comment by fffej** [comment]
I'm happy for this to be merged (and I've added `Redgate.Logging` to the retire list).

**Comment by garethbragg** [comment]
I definitely support these changes!

Do we have an `adopt` logging option somewhere?

**Comment by Greg-Smulko** [comment]
> Do we have an adopt logging option somewhere?

Yes, we have Serilog in adopt.

**Comment by garethbragg** [comment]
Thanks @Greg-Smulko, I just couldn't see it!

**Comment by ChrisLambrou** [comment]
Searching for `XmlConfigurator` in `.cs` files gives slightly more managable code search results. Not sure we can rely on every use of log4net making use of config files, though.

https://codesearch.red-gate.com/?q=XmlConfigurator&i=nope&files=%5C.cs%24&excludeFiles=&repos=

**Pull request merged**
