### PR TITLE
Release management

### LINKED ISSUE #38: Release management
* Adopt - Releasing via a single script
* Endure - Manual releases via the release app

### PR DESCRIPTION
**Pull request by smobs**
Fixes #38

### CODE REVIEW

**Comment by garethbragg** [comment]
Is there any commitment to explore releasing with Octopus Deploy? We say in the readme that we want this noted down.

**Comment by smobs** [comment]
Not as far as I know. I'll cut the line later

**Comment by fffej** [comment]
What would it take for a team to explore Octopus for deployments? (cc @rmc47 since he probably knows the answer!).

**Comment by nyctef** [comment]
IIRC when we first did the release scripts DTW project we investigated Octopus, but didn't find it provided any benefit at the time (since we're basically automating the release app / update admin rather than installing onto a specific machine with Octopus agents).

Hosted stuff like http://sqlclone.red-gate.com is released through Octopus, though - not sure about https://monitor.red-gate.com but I assume that could be as well.

**Comment by adrianbanks** [comment]
monitor.red-gate.com is deployed using Octopus, as are our internal test sites.

**Comment by fffej** [comment]
[Preview](https://radar.thoughtworks.com/?sheetId=https://raw.githubusercontent.com/red-gate/Tech-Radar/9f32099aaa27beeb7ecbb60d8a4709b8a6670c64/radar.csv)

**Pull request merged**
